#!/bin/sh

#$Id$

# Copyright (C) 2002  ken restivo <ken@restivo.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.                                  #
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


KENCLOC=/mnt/kens/ki/is/c

FILES=" 
		TO* 
		*.[ch] 
		Makefile 
		proj 
		debian/rules 
		debian/changelog
		debian/control
		debian/dirs
		debian/docs
		debian/sersnoop.sgml
"

OPTIONALS="
		/mnt/www/restivo/projects/sersnoop/index.html
"


#code starts here

for i in ${OPTIONALS}; do
	echo "checking for "${i}".."
	if [ -e "${i}" ] ; then
		FILES="${FILES} ${i}"
		echo "editing "${i}".."
	fi
done

DAY=nite

if [ "$1" ]; then
	DAY="$1"
fi

case "$DAY" in
	day)
		gvim ${FILES}
		;;
	local)
		vim ${FILES}
		;;
	*)
		kvi ${FILES}
	;;
esac

echo
echo
echo
	
#EOF

